spring:
  datasource:
    dynamic:
      primary: master #设置默认数据源或数据源组，master默认值(数据源名称可以随意起名，没有固定值，eg:db1,db2)
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        # 主数据库
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/colorxx?
          username: 123
          password: 123
          maximum-pool-size: 10
          min-idle: 1
        # 从数据库
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306
          username: 123
          password: 123
          maximum-pool-size: 10
          min-idle: 1

