# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8181
  port: 8181
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    max-swallow-size: -1MB
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 25


# 数据库配置
spring:
  #springboot多环境配置
  profiles:
    active: dev


# MyBatis配置
mybatis-plus:
  # 对应的 XML 文件位置
  #mapper-locations: classpath*:mapper/*.xml
  mapper-locations: classpath*:mapper/**.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.colorone.**.domain
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    map-underscore-to-camel-case: true

