# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8181
  port: 8181
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    max-swallow-size: -1MB
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 25

# 数据库配置
spring:
  #springboot多环境配置
  profiles:
    active: dev

  datasource:
    dynamic:
      primary: master #设置默认数据源或数据源组，master默认值(数据源名称可以随意起名，没有固定值，eg:db1,db2)
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        # 主数据库
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/colorxx?
          username: colorone
          password: colorone
          maximum-pool-size: 10
          min-idle: 1
        # 从数据库
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306
          username: colorone
          password: colorone
          maximum-pool-size: 10
          min-idle: 1

# MyBatis配置
mybatis-plus:
  # 对应的 XML 文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.colorone.**.domain
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    map-underscore-to-camel-case: true


