spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.225.55:3306/colorxx?
    username: colorxx
    password: colorxx
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-test-query: SELECT 1 FROM DUAL

  data:
    # redis缓存服务配置
    redis:
      port: 6379
      host: 127.0.0.1
      password:
      timeout: 10s
      database: 3
# 日志相配置
logging:
  level:
    com.colorone.system.mapper: debug
    root: debug